//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: authorization.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_FirstAuthorization_Req")]
  public partial class CMSG_FirstAuthorization_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_FirstAuthorization_Req() {}
    
    private ulong _account_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }
    private string _account_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account_name
    {
      get { return _account_name; }
      set { _account_name = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _channel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_FirstAuthorization_Resp")]
  public partial class SMSG_FirstAuthorization_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_FirstAuthorization_Resp() {}
    
    private uint _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }

    private string _authorization_str;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"authorization_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string authorization_str
    {
      get { return _authorization_str?? ""; }
      set { _authorization_str = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool authorization_strSpecified
    {
      get { return _authorization_str != null; }
      set { if (value == (_authorization_str== null)) _authorization_str = value ? authorization_str : (string)null; }
    }
    private bool ShouldSerializeauthorization_str() { return authorization_strSpecified; }
    private void Resetauthorization_str() { authorization_strSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_ReconnectOnLossandAuthorization_Req")]
  public partial class CMSG_ReconnectOnLossandAuthorization_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_ReconnectOnLossandAuthorization_Req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ConnectToNewGateway_Ntf")]
  public partial class SMSG_ConnectToNewGateway_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_ConnectToNewGateway_Ntf() {}
    
    private string _ip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _port;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SyncServerTimestamp_Ntf")]
  public partial class SMSG_SyncServerTimestamp_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_SyncServerTimestamp_Ntf() {}
    
    private ulong _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SyncRandomFactor_Ntf")]
  public partial class SMSG_SyncRandomFactor_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_SyncRandomFactor_Ntf() {}
    
    private string _random_factor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"random_factor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string random_factor
    {
      get { return _random_factor; }
      set { _random_factor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_AccountDuplicateLogin_Ntf")]
  public partial class SMSG_AccountDuplicateLogin_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_AccountDuplicateLogin_Ntf() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: battle.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleSyncData")]
  public partial class BattleSyncData : global::ProtoBuf.IExtensible
  {
    public BattleSyncData() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleOverData")]
  public partial class BattleOverData : global::ProtoBuf.IExtensible
  {
    public BattleOverData() {}
    
    private uint _over_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"over_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint over_type
    {
      get { return _over_type; }
      set { _over_type = value; }
    }
    private uint _star;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _win_team;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"win_team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint win_team
    {
      get { return _win_team; }
      set { _win_team = value; }
    }

    private byte[] _data;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data?? null; }
      set { _data = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dataSpecified
    {
      get { return _data != null; }
      set { if (value == (_data== null)) _data = value ? data : (byte[])null; }
    }
    private bool ShouldSerializedata() { return dataSpecified; }
    private void Resetdata() { dataSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_BattleSync_Req")]
  public partial class CMSG_BattleSync_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_BattleSync_Req() {}
    
    private readonly global::System.Collections.Generic.List<BattleSyncData> _list = new global::System.Collections.Generic.List<BattleSyncData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BattleSyncData> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_BattleSync_Ntf")]
  public partial class SMSG_BattleSync_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_BattleSync_Ntf() {}
    
    private readonly global::System.Collections.Generic.List<BattleSyncData> _list = new global::System.Collections.Generic.List<BattleSyncData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BattleSyncData> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_BattleOver_Req")]
  public partial class CMSG_BattleOver_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_BattleOver_Req() {}
    
    private BattleOverData _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BattleOverData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_BattleOver_Ntf")]
  public partial class SMSG_BattleOver_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_BattleOver_Ntf() {}
    
    private BattleOverData _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BattleOverData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_EnterCopy_Req")]
  public partial class CMSG_EnterCopy_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_EnterCopy_Req() {}
    
    private uint _copy_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"copy_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint copy_id
    {
      get { return _copy_id; }
      set { _copy_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_EnterCopy_Resp")]
  public partial class SMSG_EnterCopy_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_EnterCopy_Resp() {}
    
    private uint _copy_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"copy_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint copy_id
    {
      get { return _copy_id; }
      set { _copy_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: character.proto
// Note: requires additional types generated from: hero.proto
// Note: requires additional types generated from: item.proto
// Note: requires additional types generated from: trap.proto
// Note: requires additional types generated from: skill.proto
// Note: requires additional types generated from: equipment.proto
// Note: requires additional types generated from: copy.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterInfo")]
  public partial class CharacterInfo : global::ProtoBuf.IExtensible
  {
    public CharacterInfo() {}
    
    private ulong _account_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }
    private ulong _char_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _portrait;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"portrait", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint portrait
    {
      get { return _portrait; }
      set { _portrait = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private ulong _exp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private ulong _non_bind_gold;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"non_bind_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong non_bind_gold
    {
      get { return _non_bind_gold; }
      set { _non_bind_gold = value; }
    }
    private ulong _bind_gold;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"bind_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong bind_gold
    {
      get { return _bind_gold; }
      set { _bind_gold = value; }
    }
    private ulong _non_bind_diamond;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"non_bind_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong non_bind_diamond
    {
      get { return _non_bind_diamond; }
      set { _non_bind_diamond = value; }
    }
    private ulong _bind_diamond;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"bind_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong bind_diamond
    {
      get { return _bind_diamond; }
      set { _bind_diamond = value; }
    }
    private uint _physical_strength;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"physical_strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint physical_strength
    {
      get { return _physical_strength; }
      set { _physical_strength = value; }
    }
    private ulong _fight_point;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"fight_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong fight_point
    {
      get { return _fight_point; }
      set { _fight_point = value; }
    }
    private uint _flags;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint flags
    {
      get { return _flags; }
      set { _flags = value; }
    }
    private uint _curr_selected_hero_id;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"curr_selected_hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint curr_selected_hero_id
    {
      get { return _curr_selected_hero_id; }
      set { _curr_selected_hero_id = value; }
    }
    private uint _x;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }
    private uint _y;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private uint _prison_level;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"prison_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint prison_level
    {
      get { return _prison_level; }
      set { _prison_level = value; }
    }
    private ulong _prison_exp;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"prison_exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong prison_exp
    {
      get { return _prison_exp; }
      set { _prison_exp = value; }
    }
    private uint _prison_tech_points;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"prison_tech_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint prison_tech_points
    {
      get { return _prison_tech_points; }
      set { _prison_tech_points = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SyncRoleInfo_Ntf")]
  public partial class SMSG_SyncRoleInfo_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_SyncRoleInfo_Ntf() {}
    
    private CharacterInfo _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CharacterInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private readonly global::System.Collections.Generic.List<HeroInfo> _hero_list = new global::System.Collections.Generic.List<HeroInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"hero_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HeroInfo> hero_list
    {
      get { return _hero_list; }
    }
  
    private readonly global::System.Collections.Generic.List<ItemInfo> _item_list = new global::System.Collections.Generic.List<ItemInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"item_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ItemInfo> item_list
    {
      get { return _item_list; }
    }
  
    private readonly global::System.Collections.Generic.List<TrapInfo> _trap_list = new global::System.Collections.Generic.List<TrapInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"trap_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TrapInfo> trap_list
    {
      get { return _trap_list; }
    }
  
    private readonly global::System.Collections.Generic.List<EquipmentInfo> _equipment_list = new global::System.Collections.Generic.List<EquipmentInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"equipment_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipmentInfo> equipment_list
    {
      get { return _equipment_list; }
    }
  
    private readonly global::System.Collections.Generic.List<SkillInfo> _skill_list = new global::System.Collections.Generic.List<SkillInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"skill_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SkillInfo> skill_list
    {
      get { return _skill_list; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _trap_list_by_single = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"trap_list_by_single", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> trap_list_by_single
    {
      get { return _trap_list_by_single; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _trap_list_by_team_copy = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"trap_list_by_team_copy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> trap_list_by_team_copy
    {
      get { return _trap_list_by_team_copy; }
    }
  
    private readonly global::System.Collections.Generic.List<CopyInfo> _copy_list = new global::System.Collections.Generic.List<CopyInfo>();
    [global::ProtoBuf.ProtoMember(9, Name=@"copy_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CopyInfo> copy_list
    {
      get { return _copy_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_AddExpByPlayer_Ntf")]
  public partial class SMSG_AddExpByPlayer_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_AddExpByPlayer_Ntf() {}
    
    private ulong _exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_LevelingUpByPlayer_Ntf")]
  public partial class SMSG_LevelingUpByPlayer_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_LevelingUpByPlayer_Ntf() {}
    
    private uint _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_RemoveCoin_Ntf")]
  public partial class SMSG_RemoveCoin_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_RemoveCoin_Ntf() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private ulong _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SyncPhysicalStrength_Ntf")]
  public partial class SMSG_SyncPhysicalStrength_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_SyncPhysicalStrength_Ntf() {}
    
    private uint _physical_strength;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"physical_strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint physical_strength
    {
      get { return _physical_strength; }
      set { _physical_strength = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: chat.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_ChannelChat_Req")]
  public partial class CMSG_ChannelChat_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_ChannelChat_Req() {}
    
    private uint _channel_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint channel_type
    {
      get { return _channel_type; }
      set { _channel_type = value; }
    }

    private ulong? _to_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"to_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong to_id
    {
      get { return _to_id?? default(ulong); }
      set { _to_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool to_idSpecified
    {
      get { return _to_id != null; }
      set { if (value == (_to_id== null)) _to_id = value ? to_id : (ulong?)null; }
    }
    private bool ShouldSerializeto_id() { return to_idSpecified; }
    private void Resetto_id() { to_idSpecified = false; }
    

    private string _to_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"to_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string to_name
    {
      get { return _to_name?? ""; }
      set { _to_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool to_nameSpecified
    {
      get { return _to_name != null; }
      set { if (value == (_to_name== null)) _to_name = value ? to_name : (string)null; }
    }
    private bool ShouldSerializeto_name() { return to_nameSpecified; }
    private void Resetto_name() { to_nameSpecified = false; }
    

    private string _content;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content?? ""; }
      set { _content = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool contentSpecified
    {
      get { return _content != null; }
      set { if (value == (_content== null)) _content = value ? content : (string)null; }
    }
    private bool ShouldSerializecontent() { return contentSpecified; }
    private void Resetcontent() { contentSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ChannelChat_Resp")]
  public partial class SMSG_ChannelChat_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_ChannelChat_Resp() {}
    
    private uint _channel_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint channel_type
    {
      get { return _channel_type; }
      set { _channel_type = value; }
    }

    private ulong? _to_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"to_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong to_id
    {
      get { return _to_id?? default(ulong); }
      set { _to_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool to_idSpecified
    {
      get { return _to_id != null; }
      set { if (value == (_to_id== null)) _to_id = value ? to_id : (ulong?)null; }
    }
    private bool ShouldSerializeto_id() { return to_idSpecified; }
    private void Resetto_id() { to_idSpecified = false; }
    

    private string _to_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"to_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string to_name
    {
      get { return _to_name?? ""; }
      set { _to_name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool to_nameSpecified
    {
      get { return _to_name != null; }
      set { if (value == (_to_name== null)) _to_name = value ? to_name : (string)null; }
    }
    private bool ShouldSerializeto_name() { return to_nameSpecified; }
    private void Resetto_name() { to_nameSpecified = false; }
    

    private string _content;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content?? ""; }
      set { _content = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool contentSpecified
    {
      get { return _content != null; }
      set { if (value == (_content== null)) _content = value ? content : (string)null; }
    }
    private bool ShouldSerializecontent() { return contentSpecified; }
    private void Resetcontent() { contentSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: common.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ErrorCode_Ntf")]
  public partial class SMSG_ErrorCode_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_ErrorCode_Ntf() {}
    
    private uint _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: copy.proto
// Note: requires additional types generated from: item.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_AddItem_Req")]
  public partial class CMSG_AddItem_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_AddItem_Req() {}
    
    private readonly global::System.Collections.Generic.List<ItemInfo> _item_list = new global::System.Collections.Generic.List<ItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ItemInfo> item_list
    {
      get { return _item_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyInfo")]
  public partial class CopyInfo : global::ProtoBuf.IExtensible
  {
    public CopyInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _reset_counter;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reset_counter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reset_counter
    {
      get { return _reset_counter; }
      set { _reset_counter = value; }
    }
    private uint _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private uint _star_counter;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"star_counter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star_counter
    {
      get { return _star_counter; }
      set { _star_counter = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: equipment.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipmentInfo")]
  public partial class EquipmentInfo : global::ProtoBuf.IExtensible
  {
    public EquipmentInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_AddEquipment_Ntf")]
  public partial class SMSG_AddEquipment_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_AddEquipment_Ntf() {}
    
    private EquipmentInfo _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public EquipmentInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: hero.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfo")]
  public partial class HeroInfo : global::ProtoBuf.IExtensible
  {
    public HeroInfo() {}
    
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private uint _model_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"model_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint model_id
    {
      get { return _model_id; }
      set { _model_id = value; }
    }
    private uint _fashion_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fashion_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fashion_id
    {
      get { return _fashion_id; }
      set { _fashion_id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _skill_point;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"skill_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skill_point
    {
      get { return _skill_point; }
      set { _skill_point = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _equipment_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"equipment_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> equipment_list
    {
      get { return _equipment_list; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _skill_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"skill_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> skill_list
    {
      get { return _skill_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_SelectInitializedHero_Req")]
  public partial class CMSG_SelectInitializedHero_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_SelectInitializedHero_Req() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SelectInitializedHero_Resp")]
  public partial class SMSG_SelectInitializedHero_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_SelectInitializedHero_Resp() {}
    
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_AddHero_Ntf")]
  public partial class SMSG_AddHero_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_AddHero_Ntf() {}
    
    private HeroInfo _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public HeroInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_UnitLevelingUp_Req")]
  public partial class CMSG_UnitLevelingUp_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_UnitLevelingUp_Req() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_UnitLevelingUp_Resp")]
  public partial class SMSG_UnitLevelingUp_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_UnitLevelingUp_Resp() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private uint? _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level?? default(uint); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return _level != null; }
      set { if (value == (_level== null)) _level = value ? level : (uint?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    

    private uint? _prison_level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"prison_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint prison_level
    {
      get { return _prison_level?? default(uint); }
      set { _prison_level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool prison_levelSpecified
    {
      get { return _prison_level != null; }
      set { if (value == (_prison_level== null)) _prison_level = value ? prison_level : (uint?)null; }
    }
    private bool ShouldSerializeprison_level() { return prison_levelSpecified; }
    private void Resetprison_level() { prison_levelSpecified = false; }
    

    private uint? _prison_exp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"prison_exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint prison_exp
    {
      get { return _prison_exp?? default(uint); }
      set { _prison_exp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool prison_expSpecified
    {
      get { return _prison_exp != null; }
      set { if (value == (_prison_exp== null)) _prison_exp = value ? prison_exp : (uint?)null; }
    }
    private bool ShouldSerializeprison_exp() { return prison_expSpecified; }
    private void Resetprison_exp() { prison_expSpecified = false; }
    

    private uint? _prison_tech_points;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"prison_tech_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint prison_tech_points
    {
      get { return _prison_tech_points?? default(uint); }
      set { _prison_tech_points = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool prison_tech_pointsSpecified
    {
      get { return _prison_tech_points != null; }
      set { if (value == (_prison_tech_points== null)) _prison_tech_points = value ? prison_tech_points : (uint?)null; }
    }
    private bool ShouldSerializeprison_tech_points() { return prison_tech_pointsSpecified; }
    private void Resetprison_tech_points() { prison_tech_pointsSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_HeroSetting_Req")]
  public partial class CMSG_HeroSetting_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_HeroSetting_Req() {}
    
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private uint _operation_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"operation_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint operation_type
    {
      get { return _operation_type; }
      set { _operation_type = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _position;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_HeroSetting_Resp")]
  public partial class SMSG_HeroSetting_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_HeroSetting_Resp() {}
    
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private uint _operation_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"operation_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint operation_type
    {
      get { return _operation_type; }
      set { _operation_type = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _position;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_SelectHeroByBattleFormation_Req")]
  public partial class CMSG_SelectHeroByBattleFormation_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_SelectHeroByBattleFormation_Req() {}
    
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SelectHeroByBattleFormation_Resp")]
  public partial class SMSG_SelectHeroByBattleFormation_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_SelectHeroByBattleFormation_Resp() {}
    
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_HeroSkillLevelingUp_Req")]
  public partial class CMSG_HeroSkillLevelingUp_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_HeroSkillLevelingUp_Req() {}
    
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private uint _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_HeroSkillLevelingUp_Resp")]
  public partial class SMSG_HeroSkillLevelingUp_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_HeroSkillLevelingUp_Resp() {}
    
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private uint _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _skill_point;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"skill_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skill_point
    {
      get { return _skill_point; }
      set { _skill_point = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_ResetHeroSkillLevel_Req")]
  public partial class CMSG_ResetHeroSkillLevel_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_ResetHeroSkillLevel_Req() {}
    
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ResetHeroSkillLevel_Resp")]
  public partial class SMSG_ResetHeroSkillLevel_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_ResetHeroSkillLevel_Resp() {}
    
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private uint _skill_point;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skill_point
    {
      get { return _skill_point; }
      set { _skill_point = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: item.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemInfo")]
  public partial class ItemInfo : global::ProtoBuf.IExtensible
  {
    public ItemInfo() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_AddItem_Ntf")]
  public partial class SMSG_AddItem_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_AddItem_Ntf() {}
    
    private readonly global::System.Collections.Generic.List<ItemInfo> _item_list = new global::System.Collections.Generic.List<ItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ItemInfo> item_list
    {
      get { return _item_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_RemoveItem_Ntf")]
  public partial class SMSG_RemoveItem_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_RemoveItem_Ntf() {}
    
    private readonly global::System.Collections.Generic.List<ItemInfo> _item_list = new global::System.Collections.Generic.List<ItemInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ItemInfo> item_list
    {
      get { return _item_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: package.proto
namespace Games.PB
{
}
// Generated from: skill.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillInfo")]
  public partial class SkillInfo : global::ProtoBuf.IExtensible
  {
    public SkillInfo() {}
    
    private uint _skill_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: team.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_CreateTeamCopy_Req")]
  public partial class CMSG_CreateTeamCopy_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_CreateTeamCopy_Req() {}
    
    private uint _copy_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"copy_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint copy_id
    {
      get { return _copy_id; }
      set { _copy_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_CreateTeamCopy_Resp")]
  public partial class SMSG_CreateTeamCopy_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_CreateTeamCopy_Resp() {}
    
    private uint _copy_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"copy_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint copy_id
    {
      get { return _copy_id; }
      set { _copy_id = value; }
    }
    private uint _team_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"team_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint team_id
    {
      get { return _team_id; }
      set { _team_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_SignUpTeamCopy_Req")]
  public partial class CMSG_SignUpTeamCopy_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_SignUpTeamCopy_Req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SignUpTeamCopy_Resp")]
  public partial class SMSG_SignUpTeamCopy_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_SignUpTeamCopy_Resp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_CancelTeamCopy_Req")]
  public partial class CMSG_CancelTeamCopy_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_CancelTeamCopy_Req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_CancelTeamCopy_Resp")]
  public partial class SMSG_CancelTeamCopy_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_CancelTeamCopy_Resp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeamPlayerInfo")]
  public partial class TeamPlayerInfo : global::ProtoBuf.IExtensible
  {
    public TeamPlayerInfo() {}
    
    private ulong _char_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _trap_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"trap_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> trap_list
    {
      get { return _trap_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_TeamPrepareEnterRoom_Ntf")]
  public partial class SMSG_TeamPrepareEnterRoom_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_TeamPrepareEnterRoom_Ntf() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _countdown;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"countdown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint countdown
    {
      get { return _countdown; }
      set { _countdown = value; }
    }
    private readonly global::System.Collections.Generic.List<TeamPlayerInfo> _player_list = new global::System.Collections.Generic.List<TeamPlayerInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"player_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TeamPlayerInfo> player_list
    {
      get { return _player_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_TeamPrepareStatusChanged_Ntf")]
  public partial class SMSG_TeamPrepareStatusChanged_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_TeamPrepareStatusChanged_Ntf() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_LeaveTeamCopy_Req")]
  public partial class CMSG_LeaveTeamCopy_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_LeaveTeamCopy_Req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_LeaveTeamCopy_Resp")]
  public partial class SMSG_LeaveTeamCopy_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_LeaveTeamCopy_Resp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_LeaveTeamCopy_Ntf")]
  public partial class SMSG_LeaveTeamCopy_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_LeaveTeamCopy_Ntf() {}
    
    private ulong _char_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_ConfirmEnteringTeamCopy_Req")]
  public partial class CMSG_ConfirmEnteringTeamCopy_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_ConfirmEnteringTeamCopy_Req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ConfirmEnteringTeamCopy_Resp")]
  public partial class SMSG_ConfirmEnteringTeamCopy_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_ConfirmEnteringTeamCopy_Resp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_RefuseEnteringTeamCopy_Req")]
  public partial class CMSG_RefuseEnteringTeamCopy_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_RefuseEnteringTeamCopy_Req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_RefuseEnteringTeamCopy_Resp")]
  public partial class SMSG_RefuseEnteringTeamCopy_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_RefuseEnteringTeamCopy_Resp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ReturnSignUpInterface_Ntf")]
  public partial class SMSG_ReturnSignUpInterface_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_ReturnSignUpInterface_Ntf() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_EnterMatchingStateTeamCopy_Ntf")]
  public partial class SMSG_EnterMatchingStateTeamCopy_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_EnterMatchingStateTeamCopy_Ntf() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ChangeLeaderTeamCopy_Ntf")]
  public partial class SMSG_ChangeLeaderTeamCopy_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_ChangeLeaderTeamCopy_Ntf() {}
    
    private ulong _char_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SyncRoomState_Ntf")]
  public partial class SMSG_SyncRoomState_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_SyncRoomState_Ntf() {}
    
    private ulong _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_EnterTeamCopy_Ntf")]
  public partial class SMSG_EnterTeamCopy_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_EnterTeamCopy_Ntf() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_LoadingProgress_Req")]
  public partial class CMSG_LoadingProgress_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_LoadingProgress_Req() {}
    
    private uint _progress;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SyncLoadingProgress_Ntf")]
  public partial class SMSG_SyncLoadingProgress_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_SyncLoadingProgress_Ntf() {}
    
    private ulong _char_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private uint _progress;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_StartGameTeamCopy_Ntf")]
  public partial class SMSG_StartGameTeamCopy_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_StartGameTeamCopy_Ntf() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_ConfirmPreparingEnterGame_Req")]
  public partial class CMSG_ConfirmPreparingEnterGame_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_ConfirmPreparingEnterGame_Req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ConfirmPreparingEnterGame_Resp")]
  public partial class SMSG_ConfirmPreparingEnterGame_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_ConfirmPreparingEnterGame_Resp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SyncPlayerBattleFormationByTeamCopy_Ntf")]
  public partial class SMSG_SyncPlayerBattleFormationByTeamCopy_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_SyncPlayerBattleFormationByTeamCopy_Ntf() {}
    
    private ulong _char_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _trap_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"trap_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> trap_list
    {
      get { return _trap_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: trap.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrapInfo")]
  public partial class TrapInfo : global::ProtoBuf.IExtensible
  {
    public TrapInfo() {}
    
    private uint _trap_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"trap_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint trap_id
    {
      get { return _trap_id; }
      set { _trap_id = value; }
    }
    private uint _model_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"model_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint model_id
    {
      get { return _model_id; }
      set { _model_id = value; }
    }
    private uint _fashion_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fashion_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fashion_id
    {
      get { return _fashion_id; }
      set { _fashion_id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _active_skills = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"active_skills", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> active_skills
    {
      get { return _active_skills; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_AddTrap_Ntf")]
  public partial class SMSG_AddTrap_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_AddTrap_Ntf() {}
    
    private TrapInfo _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TrapInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_ActivePrisonSkill_Req")]
  public partial class CMSG_ActivePrisonSkill_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_ActivePrisonSkill_Req() {}
    
    private uint _trap_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"trap_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint trap_id
    {
      get { return _trap_id; }
      set { _trap_id = value; }
    }
    private uint _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ActivePrisonSkill_Resp")]
  public partial class SMSG_ActivePrisonSkill_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_ActivePrisonSkill_Resp() {}
    
    private uint _trap_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"trap_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint trap_id
    {
      get { return _trap_id; }
      set { _trap_id = value; }
    }
    private uint _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private uint _prison_tech_points;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"prison_tech_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint prison_tech_points
    {
      get { return _prison_tech_points; }
      set { _prison_tech_points = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_ClosePrisonSkill_Req")]
  public partial class CMSG_ClosePrisonSkill_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_ClosePrisonSkill_Req() {}
    
    private uint _trap_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"trap_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint trap_id
    {
      get { return _trap_id; }
      set { _trap_id = value; }
    }
    private uint _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ClosePrisonSkill_Resp")]
  public partial class SMSG_ClosePrisonSkill_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_ClosePrisonSkill_Resp() {}
    
    private uint _trap_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"trap_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint trap_id
    {
      get { return _trap_id; }
      set { _trap_id = value; }
    }
    private uint _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private uint _prison_tech_points;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"prison_tech_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint prison_tech_points
    {
      get { return _prison_tech_points; }
      set { _prison_tech_points = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_ResetPrisonSkill_Req")]
  public partial class CMSG_ResetPrisonSkill_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_ResetPrisonSkill_Req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ResetPrisonSkill_Resp")]
  public partial class SMSG_ResetPrisonSkill_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_ResetPrisonSkill_Resp() {}
    
    private uint _prison_tech_points;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"prison_tech_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint prison_tech_points
    {
      get { return _prison_tech_points; }
      set { _prison_tech_points = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}